library(RODBC)
library(gapindex)

channel <- gapindex::oracle_connect()
RODBC::sqlQuery(sql_channel <- gapindex::get_connected(),
                       query =
#all hauls                         
               "SELECT RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.START_LATITUDE, RACEBASE_HAUL.END_LATITUDE, RACEBASE_HAUL.START_LONGITUDE, RACEBASE_HAUL.END_LONGITUDE, RACEBASE_HAUL.BOTTOM_DEPTH, RACEBASE_HAUL.GEAR_TEMPERATURE
FROM RACEBASE_HAUL
WHERE (((RACEBASE_HAUL.REGION)='GOA' OR (RACEBASE_HAUL.REGION)='AI') AND ((RACEBASE_HAUL.CRUISE)>199000) AND ((RACEBASE_HAUL.BOTTOM_DEPTH)>0) AND ((RACEBASE_HAUL.GEAR_TEMPERATURE)>=0) AND ((RACEBASE_HAUL.PERFORMANCE)>=0) AND ((RACEBASE_HAUL.HAUL_TYPE)=3))
;"         
               )

#dusky_catch
"SELECT RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.START_LATITUDE, RACEBASE_HAUL.END_LATITUDE, RACEBASE_HAUL.START_LONGITUDE, RACEBASE_HAUL.END_LONGITUDE, RACEBASE_HAUL.BOTTOM_DEPTH, RACEBASE_HAUL.GEAR_TEMPERATURE, Log(RACEBASE_CATCH!NUMBER_FISH/(RACEBASE_HAUL!NET_WIDTH*RACEBASE_HAUL!DISTANCE_FISHED*1000/10000)+1) AS dusky
FROM RACEBASE_HAUL LEFT JOIN RACEBASE_CATCH ON RACEBASE_HAUL.HAULJOIN = RACEBASE_CATCH.HAULJOIN
WHERE (((RACEBASE_HAUL.REGION)="GOA" Or (RACEBASE_HAUL.REGION)="AI") AND ((RACEBASE_HAUL.CRUISE)>199000) AND ((RACEBASE_HAUL.BOTTOM_DEPTH)>=0) AND ((RACEBASE_HAUL.GEAR_TEMPERATURE)>=0) AND ((RACEBASE_HAUL.HAUL_TYPE)=3) AND ((RACEBASE_HAUL.PERFORMANCE)>=0) AND ((RACEBASE_CATCH.SPECIES_CODE)=30152));
"

#nrf_catch
"SELECT RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.START_LATITUDE, RACEBASE_HAUL.END_LATITUDE, RACEBASE_HAUL.START_LONGITUDE, RACEBASE_HAUL.END_LONGITUDE, RACEBASE_HAUL.BOTTOM_DEPTH, RACEBASE_HAUL.GEAR_TEMPERATURE, Log(RACEBASE_CATCH!NUMBER_FISH/(RACEBASE_HAUL!NET_WIDTH*RACEBASE_HAUL!DISTANCE_FISHED*1000/10000)+1) AS nrf
FROM RACEBASE_HAUL LEFT JOIN RACEBASE_CATCH ON RACEBASE_HAUL.HAULJOIN = RACEBASE_CATCH.HAULJOIN
WHERE (((RACEBASE_HAUL.REGION)="GOA" Or (RACEBASE_HAUL.REGION)="AI") AND ((RACEBASE_HAUL.CRUISE)>199000) AND ((RACEBASE_HAUL.BOTTOM_DEPTH)>=0) AND ((RACEBASE_HAUL.GEAR_TEMPERATURE)>=0) AND ((RACEBASE_HAUL.HAUL_TYPE)=3) AND ((RACEBASE_HAUL.PERFORMANCE)>=0) AND ((RACEBASE_CATCH.SPECIES_CODE)=30420) AND ((RACEBASE_CATCH.NUMBER_FISH) Is Not Null));
"

#pop_adult_lengths
"SELECT RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.HAUL_TYPE, RACEBASE_HAUL.PERFORMANCE, RACEBASE_LENGTH.SPECIES_CODE, Sum(RACEBASE_LENGTH.FREQUENCY) AS SumOfFREQUENCY
FROM RACEBASE_HAUL LEFT JOIN RACEBASE_LENGTH ON RACEBASE_HAUL.HAULJOIN = RACEBASE_LENGTH.HAULJOIN
WHERE (((RACEBASE_LENGTH.LENGTH)>250))
GROUP BY RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.HAUL_TYPE, RACEBASE_HAUL.PERFORMANCE, RACEBASE_LENGTH.SPECIES_CODE
HAVING (((RACEBASE_HAUL.REGION)="GOA" Or (RACEBASE_HAUL.REGION)="AI") AND ((RACEBASE_HAUL.CRUISE)>199000) AND ((RACEBASE_HAUL.HAUL_TYPE)=3) AND ((RACEBASE_HAUL.PERFORMANCE)>=0) AND ((RACEBASE_LENGTH.SPECIES_CODE)=30060));
"

#pop_catch_adult
"SELECT pop_catch_all.HAULJOIN, pop_catch_all.REGION, pop_catch_all.CRUISE, pop_catch_all.START_LATITUDE, pop_catch_all.END_LATITUDE, pop_catch_all.START_LONGITUDE, pop_catch_all.END_LONGITUDE, pop_catch_all.BOTTOM_DEPTH, pop_catch_all.GEAR_TEMPERATURE, Log((pop_percent_adult!percent_adult*pop_catch_all!NUMBER_FISH)/(pop_catch_all!NET_WIDTH*pop_catch_all!DISTANCE_FISHED*1000/10000)+1) AS pop_adult
FROM pop_catch_all LEFT JOIN pop_percent_adult ON pop_catch_all.HAULJOIN = pop_percent_adult.HAULJOIN;
"

#pop_catch_all
"SELECT RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.NET_WIDTH, RACEBASE_HAUL.DISTANCE_FISHED, RACEBASE_HAUL.START_LATITUDE, RACEBASE_HAUL.END_LATITUDE, RACEBASE_HAUL.START_LONGITUDE, RACEBASE_HAUL.END_LONGITUDE, RACEBASE_HAUL.BOTTOM_DEPTH, RACEBASE_HAUL.GEAR_TEMPERATURE, RACEBASE_CATCH.NUMBER_FISH, Log(RACEBASE_CATCH!NUMBER_FISH/(RACEBASE_HAUL!NET_WIDTH*RACEBASE_HAUL!DISTANCE_FISHED*1000/10000)+1) AS pop
FROM RACEBASE_HAUL LEFT JOIN RACEBASE_CATCH ON RACEBASE_HAUL.HAULJOIN = RACEBASE_CATCH.HAULJOIN
WHERE (((RACEBASE_HAUL.REGION)="GOA" Or (RACEBASE_HAUL.REGION)="AI") AND ((RACEBASE_HAUL.CRUISE)>199000) AND ((RACEBASE_HAUL.BOTTOM_DEPTH)>=0) AND ((RACEBASE_HAUL.GEAR_TEMPERATURE)>=0) AND ((RACEBASE_HAUL.HAUL_TYPE)=3) AND ((RACEBASE_HAUL.PERFORMANCE)>=0) AND ((RACEBASE_CATCH.SPECIES_CODE)=30060));
"

#pop_catch_juv
"SELECT pop_catch_all.HAULJOIN, pop_catch_all.REGION, pop_catch_all.CRUISE, pop_catch_all.START_LATITUDE, pop_catch_all.END_LATITUDE, pop_catch_all.START_LONGITUDE, pop_catch_all.END_LONGITUDE, pop_catch_all.BOTTOM_DEPTH, pop_catch_all.GEAR_TEMPERATURE, Log(((1-pop_percent_adult!percent_adult)*pop_catch_all!NUMBER_FISH)/(pop_catch_all!NET_WIDTH*pop_catch_all!DISTANCE_FISHED*1000/10000)+1) AS juv_pop
FROM pop_catch_all LEFT JOIN pop_percent_adult ON pop_catch_all.HAULJOIN = pop_percent_adult.HAULJOIN;
"

#pop_lengths_all
"SELECT RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.HAUL_TYPE, RACEBASE_HAUL.PERFORMANCE, RACEBASE_LENGTH.SPECIES_CODE, Sum(RACEBASE_LENGTH.FREQUENCY) AS SumOfFREQUENCY
FROM RACEBASE_HAUL LEFT JOIN RACEBASE_LENGTH ON RACEBASE_HAUL.HAULJOIN=RACEBASE_LENGTH.HAULJOIN
GROUP BY RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.HAUL_TYPE, RACEBASE_HAUL.PERFORMANCE, RACEBASE_LENGTH.SPECIES_CODE
HAVING (((RACEBASE_HAUL.REGION)="GOA" Or (RACEBASE_HAUL.REGION)="AI") AND ((RACEBASE_HAUL.CRUISE)>199000) AND ((RACEBASE_HAUL.HAUL_TYPE)=3) AND ((RACEBASE_HAUL.PERFORMANCE)>=0) AND ((RACEBASE_LENGTH.SPECIES_CODE)=30060));
"

#pop_percent_adult
"SELECT pop_lengths_all.HAULJOIN, pop_adult_lengths!SumOfFREQUENCY/pop_lengths_all!SumOfFREQUENCY AS percent_adult
FROM pop_lengths_all INNER JOIN pop_adult_lengths ON pop_lengths_all.HAULJOIN=pop_adult_lengths.HAULJOIN;
"

#re_adult_lengths
"SELECT RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.HAUL_TYPE, RACEBASE_HAUL.PERFORMANCE, Sum(RACEBASE_LENGTH.FREQUENCY) AS SumOfFREQUENCY
FROM RACEBASE_HAUL LEFT JOIN RACEBASE_LENGTH ON RACEBASE_HAUL.HAULJOIN = RACEBASE_LENGTH.HAULJOIN
WHERE (((RACEBASE_LENGTH.SPECIES_CODE)=30050 Or (RACEBASE_LENGTH.SPECIES_CODE)=30051 Or (RACEBASE_LENGTH.SPECIES_CODE)=30052) AND ((RACEBASE_LENGTH.LENGTH)>439))
GROUP BY RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.HAUL_TYPE, RACEBASE_HAUL.PERFORMANCE
HAVING (((RACEBASE_HAUL.REGION)="GOA" Or (RACEBASE_HAUL.REGION)="AI") AND ((RACEBASE_HAUL.CRUISE)>199000) AND ((RACEBASE_HAUL.HAUL_TYPE)=3) AND ((RACEBASE_HAUL.PERFORMANCE)>=0));
"

#re_catch_adult
"SELECT re_catch_all.HAULJOIN, re_catch_all.REGION, re_catch_all.CRUISE, re_catch_all.START_LATITUDE, re_catch_all.END_LATITUDE, re_catch_all.START_LONGITUDE, re_catch_all.END_LONGITUDE, re_catch_all.BOTTOM_DEPTH, re_catch_all.GEAR_TEMPERATURE, Log((re_percent_adult!percent_adult*re_catch_all!NUMBER_FISH)/(re_catch_all!NET_WIDTH*re_catch_all!DISTANCE_FISHED*1000/10000)+1) AS re_adult
FROM re_catch_all LEFT JOIN re_percent_adult ON re_catch_all.HAULJOIN = re_percent_adult.HAULJOIN;
"

#re_catch_all
"SELECT RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.NET_WIDTH, RACEBASE_HAUL.DISTANCE_FISHED, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.START_LATITUDE, RACEBASE_HAUL.END_LATITUDE, RACEBASE_HAUL.START_LONGITUDE, RACEBASE_HAUL.END_LONGITUDE, RACEBASE_HAUL.BOTTOM_DEPTH, RACEBASE_HAUL.GEAR_TEMPERATURE, Sum(RACEBASE_CATCH.NUMBER_FISH) AS NUMBER_FISH
FROM RACEBASE_HAUL LEFT JOIN RACEBASE_CATCH ON RACEBASE_HAUL.HAULJOIN = RACEBASE_CATCH.HAULJOIN
WHERE (((RACEBASE_CATCH.SPECIES_CODE)=30051 Or (RACEBASE_CATCH.SPECIES_CODE)=30052 Or (RACEBASE_CATCH.SPECIES_CODE)=30050))
GROUP BY RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.NET_WIDTH, RACEBASE_HAUL.DISTANCE_FISHED, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.START_LATITUDE, RACEBASE_HAUL.END_LATITUDE, RACEBASE_HAUL.START_LONGITUDE, RACEBASE_HAUL.END_LONGITUDE, RACEBASE_HAUL.BOTTOM_DEPTH, RACEBASE_HAUL.GEAR_TEMPERATURE, RACEBASE_HAUL.HAUL_TYPE, RACEBASE_HAUL.PERFORMANCE
HAVING (((RACEBASE_HAUL.REGION)="GOA" Or (RACEBASE_HAUL.REGION)="AI") AND ((RACEBASE_HAUL.CRUISE)>199000) AND ((RACEBASE_HAUL.BOTTOM_DEPTH)>=0) AND ((RACEBASE_HAUL.GEAR_TEMPERATURE)>=0) AND ((RACEBASE_HAUL.HAUL_TYPE)=3) AND ((RACEBASE_HAUL.PERFORMANCE)>=0));
"

#re_catch_juv
"SELECT re_catch_all.HAULJOIN, re_catch_all.REGION, re_catch_all.CRUISE, re_catch_all.START_LATITUDE, re_catch_all.END_LATITUDE, re_catch_all.START_LONGITUDE, re_catch_all.END_LONGITUDE, re_catch_all.BOTTOM_DEPTH, re_catch_all.GEAR_TEMPERATURE, Log(((1-re_percent_adult!percent_adult)*re_catch_all!NUMBER_FISH)/(re_catch_all!NET_WIDTH*re_catch_all!DISTANCE_FISHED*1000/10000)+1) AS re_adult
FROM re_catch_all LEFT JOIN re_percent_adult ON re_catch_all.HAULJOIN = re_percent_adult.HAULJOIN;
"

#re_lengths_all
"SELECT RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.HAUL_TYPE, RACEBASE_HAUL.PERFORMANCE, Sum(RACEBASE_LENGTH.FREQUENCY) AS SumOfFREQUENCY
FROM RACEBASE_HAUL LEFT JOIN RACEBASE_LENGTH ON RACEBASE_HAUL.HAULJOIN = RACEBASE_LENGTH.HAULJOIN
WHERE (((RACEBASE_LENGTH.SPECIES_CODE)=30050 Or (RACEBASE_LENGTH.SPECIES_CODE)=30051 Or (RACEBASE_LENGTH.SPECIES_CODE)=30052))
GROUP BY RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.HAUL_TYPE, RACEBASE_HAUL.PERFORMANCE
HAVING (((RACEBASE_HAUL.REGION)="GOA" Or (RACEBASE_HAUL.REGION)="AI") AND ((RACEBASE_HAUL.CRUISE)>199000) AND ((RACEBASE_HAUL.HAUL_TYPE)=3) AND ((RACEBASE_HAUL.PERFORMANCE)>=0));
"

#re_percent_adult
"SELECT re_adult_lengths.HAULJOIN, [re_adult_lengths]![SumOfFREQUENCY]/[re_lengths_all]![SumOfFREQUENCY] AS percent_adult
FROM re_adult_lengths INNER JOIN re_lengths_all ON re_adult_lengths.HAULJOIN = re_lengths_all.HAULJOIN;
"

#sr_catch
"SELECT RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.START_LATITUDE, RACEBASE_HAUL.END_LATITUDE, RACEBASE_HAUL.START_LONGITUDE, RACEBASE_HAUL.END_LONGITUDE, RACEBASE_HAUL.BOTTOM_DEPTH, RACEBASE_HAUL.GEAR_TEMPERATURE, Log(RACEBASE_CATCH!NUMBER_FISH/(RACEBASE_HAUL!NET_WIDTH*RACEBASE_HAUL!DISTANCE_FISHED*1000/10000)+1) AS sr
FROM RACEBASE_HAUL LEFT JOIN RACEBASE_CATCH ON RACEBASE_HAUL.HAULJOIN = RACEBASE_CATCH.HAULJOIN
WHERE (((RACEBASE_HAUL.REGION)="GOA" Or (RACEBASE_HAUL.REGION)="AI") AND ((RACEBASE_HAUL.CRUISE)>199000) AND ((RACEBASE_HAUL.BOTTOM_DEPTH)>=0) AND ((RACEBASE_HAUL.GEAR_TEMPERATURE)>=0) AND ((RACEBASE_HAUL.HAUL_TYPE)=3) AND ((RACEBASE_HAUL.PERFORMANCE)>=0) AND ((RACEBASE_CATCH.SPECIES_CODE)=30576));
"

#sst_catch
"SELECT RACEBASE_HAUL.HAULJOIN, RACEBASE_HAUL.REGION, RACEBASE_HAUL.CRUISE, RACEBASE_HAUL.START_LATITUDE, RACEBASE_HAUL.END_LATITUDE, RACEBASE_HAUL.START_LONGITUDE, RACEBASE_HAUL.END_LONGITUDE, RACEBASE_HAUL.BOTTOM_DEPTH, RACEBASE_HAUL.GEAR_TEMPERATURE, Log(RACEBASE_CATCH!NUMBER_FISH/(RACEBASE_HAUL!NET_WIDTH*RACEBASE_HAUL!DISTANCE_FISHED*1000/10000)+1) AS sst
FROM RACEBASE_HAUL LEFT JOIN RACEBASE_CATCH ON RACEBASE_HAUL.HAULJOIN = RACEBASE_CATCH.HAULJOIN
WHERE (((RACEBASE_HAUL.REGION)="GOA" Or (RACEBASE_HAUL.REGION)="AI") AND ((RACEBASE_HAUL.CRUISE)>199000) AND ((RACEBASE_HAUL.BOTTOM_DEPTH)>=0) AND ((RACEBASE_HAUL.GEAR_TEMPERATURE)>=0) AND ((RACEBASE_HAUL.HAUL_TYPE)=3) AND ((RACEBASE_HAUL.PERFORMANCE)>=0) AND ((RACEBASE_CATCH.SPECIES_CODE)=30020));
"

#Data
"SELECT [All Hauls].*, nrf_catch.nrf, dusky_catch.dusky, pop_catch_juv.juv_pop, pop_catch_adult.pop_adult, sst_catch.sst, re_catch_juv.re_adult, re_catch_adult.re_adult, sr_catch.sr, pop_catch_all.pop, re_catch_all.NUMBER_FISH AS re_num INTO test
FROM ((((((((([All Hauls] LEFT JOIN dusky_catch ON [All Hauls].HAULJOIN = dusky_catch.HAULJOIN) LEFT JOIN nrf_catch ON [All Hauls].HAULJOIN = nrf_catch.HAULJOIN) LEFT JOIN pop_catch_adult ON [All Hauls].HAULJOIN = pop_catch_adult.HAULJOIN) LEFT JOIN pop_catch_juv ON [All Hauls].HAULJOIN = pop_catch_juv.HAULJOIN) LEFT JOIN re_catch_adult ON [All Hauls].HAULJOIN = re_catch_adult.HAULJOIN) LEFT JOIN re_catch_juv ON [All Hauls].HAULJOIN = re_catch_juv.HAULJOIN) LEFT JOIN sr_catch ON [All Hauls].HAULJOIN = sr_catch.HAULJOIN) LEFT JOIN sst_catch ON [All Hauls].HAULJOIN = sst_catch.HAULJOIN) LEFT JOIN pop_catch_all ON [All Hauls].HAULJOIN = pop_catch_all.HAULJOIN) LEFT JOIN re_catch_all ON [All Hauls].HAULJOIN = re_catch_all.HAULJOIN;
"
